cache:
  pip: true
  yarn: true
  directories:
    - node_modules
jobs: 
  include:
    - name: "app" 
    language: node_js
    node_js:
      - node
    before_install:
      - nvm install 12
      - cd app
    install:
      - yarn install
    before_script:
      - cd app
    script:
      - yarn coveralls