language: python
python:
  - 3.8
node_js:
  - node
cache:
  pip: true
  yarn: true
  directories:
    - node_modules
stages:
  - test

jobs: 
  - stage: test
    name: "etl"
    before_install:
      - cd etl
    install:
      - pip install -r requirement.txt
    script:
      - python -m pytest --cov=.
  - stage: test
    name: "app"
    before_install:
      - nvm 12
      - cd app
    install:
      - yarn install
    script:
      - yarn coveralls