language: python
python:
  - 3.8
node_js:
  - node
cache:
  pip: true
  yarn: true
  directories:
    - node_modules
stages:
  - test
  - deploy

jobs: 
  - stage: test
    name: "etl"
    before_install:
      - cd etl
    install:
      - pip install -r requirements.txt
      - pip install -r dev-requirements.txt
    script:
      - pytest --cov=.
    after_success:
      - coveralls
  - stage: test
    name: "app"
    before_install:
      - nvm install 12
      - cd app
    install:
      - yarn install
    script:
      - yarn coveralls
  - stage: deploy
    name: "etl"
    before_install:
      - nvm install 12
      - cd etl
    install:
      - yarn install
    script:
      - sls deploy