[build]
    base = "./app/"
    publish = "./build/"
    command = "yarn deploy"
    functions = "./functions/"

[dev]
    command = "yarn --cwd app start"
    port = 8000
    publish = "app/public"
    