[build]
    base = "./app/"
    publish = "./build/"
    command = "yarn build"
    functions = "./functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
    command = "yarn --cwd app start"
    port = 8000
    publish = "app/public"
    